name: Version Bump and Draft Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (major.minor.patch)'
        required: true

jobs:
  typescript-version-bump:
    name: TypeScript - Version Bump
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Get package name
      id: package-name
      run: |
        PACKAGE_NAME=$(node -p "require('./typescript/package.json').name")
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_OUTPUT

    - name: Create branch
      run: |
        git checkout -b bump-typescript-version-${{ github.event.inputs.version }}

    - name: Update version
      run: |
        cd typescript
        npm version ${{ github.event.inputs.version }} --no-git-tag-version
        git add package.json

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Bump TypeScript ${{ steps.package-name.outputs.PACKAGE_NAME }} version to ${{ github.event.inputs.version }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        title: "Bump TypeScript ${{ steps.package-name.outputs.PACKAGE_NAME }} version to ${{ github.event.inputs.version }}"
        body: "This PR bumps the version of TypeScript package ${{ steps.package-name.outputs.PACKAGE_NAME }} to ${{ github.event.inputs.version }}"
        branch: "bump-typescript-version-${{ github.event.inputs.version }}"
        base: "main"

    - name: Create Draft Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create v${{ github.event.inputs.version }} \
          --draft \
          --title "TypeScript ${{ steps.package-name.outputs.PACKAGE_NAME }} v${{ github.event.inputs.version }}" \
          --notes "Release notes for TypeScript package ${{ steps.package-name.outputs.PACKAGE_NAME }} version ${{ github.event.inputs.version }}"